export const galleryImages = [
   { src: "/images/Ankor Wat.jpg", title: "Ankor Wat", description: "" },
   { src: "/images/Aruba.JPG", title: "Aruba", description: "" },
   { src: "/images/Atalaya, SC.JPG", title: "Atalaya, SC", description: "" },
   { src: "/images/Bangkok, Thailand 2.JPG", title: "Bangkok, Thailand 2", description: "" },
   { src: "/images/Bangkok, Thailand 3.JPG", title: "Bangkok, Thailand 3", description: "" },
   { src: "/images/Bangkok, Thailand.JPG", title: "Bangkok, Thailand", description: "" },
   { src: "/images/Big Beach MarathonALJan23.jpeg", title: "Big Beach Marathon, AL – Jan23", description: "I love when we’re racing together. There’s something about chasing a goal, side by side, that reminds me how good we are as a team, in this, and in life." },
   { src: "/images/Biscuit, SC.jpg", title: "Biscuit, SC", description: "" },
   { src: "/images/Cape Canaveral, FL.jpg", title: "Cape Canaveral, FL", description: "" },
   { src: "/images/Chiang Mai, Thailand.jpg", title: "Chiang Mai, Thailand", description: "" },
   { src: "/images/Data Night, Atlanta.jpg", title: "Data Night, Atlanta", description: "Years later, we’re still in love. We still carve out time for each other and find joy in the little wins." },
   { src: "/images/Florida 2.jpg", title: "Florida 2", description: "Look how happy my baby girl is, like nothing in the world could make her happier. I see that same look in you sometimes. And every time, I fall a little more." },
   { src: "/images/Florida 3.jpg", title: "Florida 3", description: "" },
   { src: "/images/Florida 4.jpg", title: "Florida 4", description: "" },
   { src: "/images/HuaHin.jpg", title: "HuaHin", description: "" },
   { src: "/images/Italy.jpeg", title: "Italy", description: "" },
   { src: "/images/Kenting, Taiwan.jpg", title: "Kenting, Taiwan", description: "" },
   { src: "/images/Khao Yai.jpg", title: "Khao Yai", description: "" },
   { src: "/images/King of Leon concert, GA.jpg", title: "King of Leon concert, GA", description: "" },
   { src: "/images/Ko Pha Ngan.jpg", title: "Ko Pha Ngan", description: "Look at us loving life, just moving through the world like borders don’t apply to us. I love traveling with you. We’ve seen so much, and somehow, it still feels like we’re just getting started." },
   { src: "/images/Koh Samui – Accident.JPG", title: "Koh Samui – Accident", description: "The bus accident. The day I almost lost you. Getting you out of that wreck is still one of the proudest moments of my life." },
   { src: "/images/Koh Samui – After accident.jpg", title: "Koh Samui – After accident", description: "After the bus accident. We cried, we hurt, but we didn’t let it break us. That’s kind of our thing, isn’t it? Making the most of even the hardest moments." },
   { src: "/images/Korat, Thailand.jpg", title: "Korat, Thailand", description: "" },
   { src: "/images/Laos.jpg", title: "Laos", description: "Laos, trekking through the jungle and stumbling into a party in the middle of nowhere. I love getting lost with you." },
   { src: "/images/Litchfield-Mar23.jpeg", title: "Litchfield – Mar23", description: "" },
   { src: "/images/Litchfield, SC.jpg", title: "Litchfield, SC", description: "" },
   { src: "/images/New Jersey – Wedding.jpg", title: "New Jersey – Wedding", description: "It’s wild how you don’t always realize, in the moment, how much something will shape your life. I knew our wedding was a big deal, but I had no idea just how good we’d be together." },
   { src: "/images/New York with Paul & Sam.jpeg", title: "New York with Paul & Sam", description: "New York with Paul & Sam — you met my best friend, didn’t run away, and somehow still liked him." },
   { src: "/images/New York.jpg", title: "New York", description: "This trip was such a rush, our first real time in New York, and I just felt alive. I get that feeling a lot with you." },
   { src: "/images/Pawley_s Island.jpg", title: "Pawley's Island", description: "Marley, the way you loved this dog was one of the many reasons I love you. I couldn’t show it then, but my heart broke the day we said goodbye." },
   { src: "/images/Phillipines - Honeymoon.jpg", title: "Phillipines – Honeymoon", description: "A full month on an island — something I’ve always wanted. I couldn’t imagine doing it with anyone else." },
   { src: "/images/PhiPhi.jpg", title: "PhiPhi", description: "Phi Phi, the place I first fell in love with Thailand. I didn’t think that memory could get any better… and then you showed up." },
   { src: "/images/Pranburi.jpg", title: "Pranburi", description: "Our trips to Pranburi on the bike. Honestly, this is where I really fell for you." },
   { src: "/images/Pranburri – Engagment.jpg", title: "Pranburri – Engagment", description: "Great hotel (my choice), perfect moment by the pool (also me), and the best decision of my life. Honestly, I nailed it." },
   { src: "/images/Reykjavik, Iceland.JPG", title: "Reykjavik, Iceland", description: "Reykjavik, Iceland, my race, my dream. I only hope I get to help make one of yours come true too." },
   { src: "/images/Shwedagon pagoda.jpg", title: "Shwedagon pagoda", description: "Shwedagon Pagoda, I loved how we moved through Asia like we owned it. Back then, borders didn’t seem to matter." },
   { src: "/images/Taiwan.jpg", title: "Taiwan", description: "Living in Taiwan was a highlight. We were in a strange place, figuring it out together, and I loved watching you thrive." },
   { src: "/images/Tampa Bay, FL.jpg", title: "Tampa Bay, FL", description: "" },
   { src: "/images/Zanzibar.jpg", title: "Zanzibar", description: "Ten years in and we celebrated by doing absolutely nothing in Zanzibar. Still, there’s no one else I’d rather do nothing with." },
];
